---
title: "Covid19-br"
author: "Rodrigo Scroferneker"
date: "25/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr);
library(magrittr);
library(tidyverse)
library(ggplot2)

df = read.csv("raw_data.csv", header = TRUE, sep = ";")

df1 <- df %>% 
      select(city_name, city_cod, state, state_cod) %>%
      unique() %>% 
      filter( state_cod != "None") %>%
      arrange(city_name)

write.csv(df1,"../../code_table.csv", row.names = FALSE)

df2 <- df %>% 
      select(date, new_cases) %>%
      arrange(date) %>%
      group_by(date) %>% 
      summarise(new_cases = sum(new_cases)) %>%
      mutate(total_cases=cumsum(new_cases))

df2 %>% filter( date != "Não informado") %>% ggplot( aes(x = factor(date), y = total_cases)) + 
  geom_line(aes(group=1)) + theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Data", y="N casos", title="Crescimento Covid19 no Brasil.") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave('../../data/cases_brasil.png', width = 20, height = 9, dpi = 100)

df2 %>% filter( date != "Não informado") %>% ggplot(aes(x = date, y = new_cases)) +
  geom_bar(stat="identity", fill="black") +
  labs(y = "Casos Novos", x = "Data", title = "Novos Casos de Covid19 Brasil") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggsave('../../data/new_cases_brasil.png', width = 20, height = 9, dpi = 100)

df3 <- df %>% 
      group_by(state) %>%
      summarise(total_casos = sum(new_cases)) %>%
      arrange(desc(total_casos)) %>% write.csv("../../data/cases_states.csv", row.names = FALSE)


splitdf <- split(df, df$state)
lapply(names(splitdf), function(x){write.csv(splitdf[[x]], file = paste("../../data/",x ,"/casos_", x, ".csv", sep = ""), row.names = FALSE)})


```